### ISSUE TITLE
Server Not Found 404

### ISSUE THREAD

**Issue by AndresApe** [Haoming02/ollama-unity#1]
Hi I was trying out the demos but I haven't been able to test any of the demos, every time the web request is made I get the server not found error.
WebException: The remote server returned an error: (404) Not Found.
System.Net.HttpWebRequest.GetResponseFromData (System.Net.WebResponseStream stream, System.Threading.CancellationToken cancellationToken) (at <e2bec1e2c81b42b3b2ee8a58b12808fc>:0)
System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts) (at <e2bec1e2c81b42b3b2ee8a58b12808fc>:0)

I haven't been able to find what could be causing the error. I was wondering if you could enlighten me about this problem

**Comment by Haoming02** [comment]
Did you install and start `Ollama` ?

https://github.com/Haoming02/ollama-unity#prerequisite

**Comment by AndresApe** [comment]
yes I did install Ollama and downloaded llama 3.1

**Comment by AndresApe** [comment]
Do I need to have Ollama running in my terminal for the tests to work? if thats the case that was most likely my error

**Comment by AndresApe** [comment]
Made it work, ty so much
